/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

//class LibraryTest {
//    @Test void someLibraryMethodReturnsTrue() {
//        Bitmap classUnderTest = new Bitmap();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//    }
//}
